import React from "react"

import img1654 from "../../assets/pdf-1654.webp"
import img827 from "../../assets/pdf-827.webp"
import img414 from "../../assets/pdf-414.webp"

export default function PDFImage() {
  return (
    <img
      src={img1654}
      alt="A image of a PDF generated by the MealMind application"
      srcSet={`
        ${img1654} 1654w,
        ${img827} 827w,
        ${img414} 414w
      `}
    />
  )
}